version: '3.8'
services:
  postgres:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: dummy-events-indexer
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: